import os
import sys
import tempfile
import unittest

ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), '..'))
sys.path.insert(0, os.path.join(ROOT, 'security_monitor'))

import security_monitor_main as sm

class SecurityMonitorTest(unittest.TestCase):
    def test_parse_nginx(self):
        line = '203.0.113.10 - - [23/Jun/2026:10:00:00 +0000] "GET /.env HTTP/1.1" 404 153 "-" "curl/8.0"'
        event = sm.parse_log_line(line, '/tmp/example.com.log')
        self.assertEqual(event['ip'], '203.0.113.10')
        self.assertEqual(event['uri'], '/.env')
        self.assertEqual(event['domain'], 'example.com')

    def test_rules_match(self):
        rules = sm.compile_rules(sm.default_rules())
        cases = [
            ('/.env', 'curl/8.0', 'dotfiles'),
            ('/../../etc/passwd', 'Mozilla/5.0', 'traversal-lfi'),
            ('/?id=1%20union%20select%201,2', 'Mozilla/5.0', 'sqli'),
            ('/?q=%3Cscript%3Ealert(1)%3C/script%3E', 'Mozilla/5.0', 'xss'),
            ('/vendor/phpunit/phpunit/src/Util/PHP/eval-stdin.php', 'Mozilla/5.0', 'webshell'),
        ]
        for uri, ua, expected in cases:
            hits = sm.match_rules({'uri': uri, 'user_agent': ua}, rules)
            self.assertIn(expected, [hit['id'] for hit in hits])

    def test_user_agent_whitelist(self):
        event = {'ip': '203.0.113.10', 'uri': '/.env', 'user_agent': 'Mozilla RizzSystem Client'}
        settings = {'whitelist_user_agents': ['RizzSystem'], 'whitelist_ips': [], 'whitelist_paths': [], 'private_ip_whitelist': False}
        self.assertTrue(sm.is_whitelisted(event, settings))

    def test_waf_output(self):
        waf = sm.build_nginx_waf(sm.default_rules())
        self.assertIn('generated by security_monitor', waf)
        self.assertIn('return 403', waf)

if __name__ == '__main__':
    unittest.main()
